---
dist: xenial
language: go
go:
- "1.12.x"
go_import_path: github.com/s-urbaniak/prometheus-adapter
env:
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
services:
- docker
jobs:
  include:
  - stage: Generate
    script:
      - make build-image
      - ./scripts/docker-build.sh make clean all
      - git diff --exit-code
