/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	metricsv1 "github.com/s-urbaniak/prometheus-adapter/pkg/apis/metrics/v1"
	versioned "github.com/s-urbaniak/prometheus-adapter/pkg/client/clientset/versioned"
	internalinterfaces "github.com/s-urbaniak/prometheus-adapter/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/s-urbaniak/prometheus-adapter/pkg/client/listers/metrics/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomMetricInformer provides access to a shared informer and lister for
// CustomMetrics.
type CustomMetricInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CustomMetricLister
}

type customMetricInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCustomMetricInformer constructs a new informer for CustomMetric type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomMetricInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomMetricInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCustomMetricInformer constructs a new informer for CustomMetric type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomMetricInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsV1().CustomMetrics().List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsV1().CustomMetrics().Watch(options)
			},
		},
		&metricsv1.CustomMetric{},
		resyncPeriod,
		indexers,
	)
}

func (f *customMetricInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomMetricInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customMetricInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&metricsv1.CustomMetric{}, f.defaultInformer)
}

func (f *customMetricInformer) Lister() v1.CustomMetricLister {
	return v1.NewCustomMetricLister(f.Informer().GetIndexer())
}
