apiVersion: v1
kind: ResourceRule
metadata:
  name: cpu
spec:
  containerLabel: container_name
  labels:
    namespace:
      resource: namespace
    node:
      resource: node
    pod_name:
      resource: pod
  nodeQuery: sum(1 - rate(node_cpu_seconds_total{mode="idle"}[1m]) * on(namespace,
    pod) group_left(node) node_namespace_pod:kube_pod_info:{node="kind-control-plane"})
    by (node)
  podQuery: sum(rate(container_cpu_usage_seconds_total{container_name="alertmanager",container_name!="POD",container_name!="",pod_name="alertmanager-main-0",pod_name!="",namespace="monitoring"}[1m]))
    by (container_name,pod_name,namespace)
  window: 0s
