/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/s-urbaniak/prometheus-adapter/pkg/apis/metrics/v1"
	scheme "github.com/s-urbaniak/prometheus-adapter/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomMetricsGetter has a method to return a CustomMetricInterface.
// A group's client should implement this interface.
type CustomMetricsGetter interface {
	CustomMetrics() CustomMetricInterface
}

// CustomMetricInterface has methods to work with CustomMetric resources.
type CustomMetricInterface interface {
	Create(*v1.CustomMetric) (*v1.CustomMetric, error)
	Update(*v1.CustomMetric) (*v1.CustomMetric, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CustomMetric, error)
	List(opts metav1.ListOptions) (*v1.CustomMetricList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CustomMetric, err error)
	CustomMetricExpansion
}

// customMetrics implements CustomMetricInterface
type customMetrics struct {
	client rest.Interface
}

// newCustomMetrics returns a CustomMetrics
func newCustomMetrics(c *MetricsV1Client) *customMetrics {
	return &customMetrics{
		client: c.RESTClient(),
	}
}

// Get takes name of the customMetric, and returns the corresponding customMetric object, and an error if there is any.
func (c *customMetrics) Get(name string, options metav1.GetOptions) (result *v1.CustomMetric, err error) {
	result = &v1.CustomMetric{}
	err = c.client.Get().
		Resource("custommetrics").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomMetrics that match those selectors.
func (c *customMetrics) List(opts metav1.ListOptions) (result *v1.CustomMetricList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CustomMetricList{}
	err = c.client.Get().
		Resource("custommetrics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customMetrics.
func (c *customMetrics) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("custommetrics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a customMetric and creates it.  Returns the server's representation of the customMetric, and an error, if there is any.
func (c *customMetrics) Create(customMetric *v1.CustomMetric) (result *v1.CustomMetric, err error) {
	result = &v1.CustomMetric{}
	err = c.client.Post().
		Resource("custommetrics").
		Body(customMetric).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customMetric and updates it. Returns the server's representation of the customMetric, and an error, if there is any.
func (c *customMetrics) Update(customMetric *v1.CustomMetric) (result *v1.CustomMetric, err error) {
	result = &v1.CustomMetric{}
	err = c.client.Put().
		Resource("custommetrics").
		Name(customMetric.Name).
		Body(customMetric).
		Do().
		Into(result)
	return
}

// Delete takes name of the customMetric and deletes it. Returns an error if one occurs.
func (c *customMetrics) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("custommetrics").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customMetrics) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("custommetrics").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customMetric.
func (c *customMetrics) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CustomMetric, err error) {
	result = &v1.CustomMetric{}
	err = c.client.Patch(pt).
		Resource("custommetrics").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
