/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/s-urbaniak/prometheus-adapter/pkg/apis/metrics/v1"
	scheme "github.com/s-urbaniak/prometheus-adapter/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceRulesGetter has a method to return a ResourceRuleInterface.
// A group's client should implement this interface.
type ResourceRulesGetter interface {
	ResourceRules() ResourceRuleInterface
}

// ResourceRuleInterface has methods to work with ResourceRule resources.
type ResourceRuleInterface interface {
	Create(*v1.ResourceRule) (*v1.ResourceRule, error)
	Update(*v1.ResourceRule) (*v1.ResourceRule, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ResourceRule, error)
	List(opts metav1.ListOptions) (*v1.ResourceRuleList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ResourceRule, err error)
	ResourceRuleExpansion
}

// resourceRules implements ResourceRuleInterface
type resourceRules struct {
	client rest.Interface
}

// newResourceRules returns a ResourceRules
func newResourceRules(c *MetricsV1Client) *resourceRules {
	return &resourceRules{
		client: c.RESTClient(),
	}
}

// Get takes name of the resourceRule, and returns the corresponding resourceRule object, and an error if there is any.
func (c *resourceRules) Get(name string, options metav1.GetOptions) (result *v1.ResourceRule, err error) {
	result = &v1.ResourceRule{}
	err = c.client.Get().
		Resource("resourcerules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceRules that match those selectors.
func (c *resourceRules) List(opts metav1.ListOptions) (result *v1.ResourceRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ResourceRuleList{}
	err = c.client.Get().
		Resource("resourcerules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceRules.
func (c *resourceRules) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("resourcerules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a resourceRule and creates it.  Returns the server's representation of the resourceRule, and an error, if there is any.
func (c *resourceRules) Create(resourceRule *v1.ResourceRule) (result *v1.ResourceRule, err error) {
	result = &v1.ResourceRule{}
	err = c.client.Post().
		Resource("resourcerules").
		Body(resourceRule).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceRule and updates it. Returns the server's representation of the resourceRule, and an error, if there is any.
func (c *resourceRules) Update(resourceRule *v1.ResourceRule) (result *v1.ResourceRule, err error) {
	result = &v1.ResourceRule{}
	err = c.client.Put().
		Resource("resourcerules").
		Name(resourceRule.Name).
		Body(resourceRule).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceRule and deletes it. Returns an error if one occurs.
func (c *resourceRules) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("resourcerules").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceRules) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("resourcerules").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceRule.
func (c *resourceRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ResourceRule, err error) {
	result = &v1.ResourceRule{}
	err = c.client.Patch(pt).
		Resource("resourcerules").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
